print("hello git! i am learning github! and i'm going to be a LLM engineer!")
print("this is the change in my new branch feature-calculator")
print("this is my PR practice")
print("these changes i did directly on github")
print("change made remotely")
print("some changes are hard to do")
print("change on master")
print("this commit is for cherry-pick")
